GET http://localhost:3001/destinations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjY2EiLCJpYXQiOjE2NTg3NjIyOTEsImV4cCI6MTY1ODc2MjMwNn0.Hw2eU_5OAj5cduO05--lGpBnlP1vwqwoQLGMaRij5OE

###

DELETE http://localhost:4000/logout
Content-Type: application/json

 {
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjY2EiLCJpYXQiOjE2NTg3NjIwNjUsImV4cCI6MTY1ODc2MjA4MH0.tPxfYApUgfQ4J3k9-4AZM6DxE3QyYooIz0WFhYpuqnI"
 }

###

POST http://localhost:4000/token
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjY2EiLCJpYXQiOjE2NTg3NjIyOTF9.Eo4u7tCKOu5Sv6VX2JyUR-Yym-lzQsF_r8Vjvo461b8"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Lucca"
}
